# Generated by Django 4.0.3 on 2022-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(default='My products details'),
        ),
    ]
