# Generated by Django 4.0.3 on 2022-03-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_item_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prod_prop',
            field=models.CharField(default='supplement', max_length=50),
        ),
    ]
