# Generated by Django 4.0.3 on 2022-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_item_prod_prop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='products/%y'),
        ),
    ]
