# Generated by Django 4.0.3 on 2022-04-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customer_rename_item_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_prop',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pain Relief', 'Pain Relief'), ('Oral Care', 'Oral Care'), ('First Aid', 'First Aid'), ('Vitamins & Minerals', 'Vitamins & Minerals'), ('Stomach & Bowel', 'Stomach & Bowel'), ('Cough, Cold & Flu', 'Cough, Cold & Flu'), ('Allergy & Hayfever', 'Allergy & Hayfever'), ('Sexual Health', 'Sexual Health')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
