# Generated by Django 4.0.3 on 2022-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_product_img_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pain Relief', 'Pain Relief'), ('Oral Care', 'Oral Care'), ('First Aid', 'First Aid'), ('Vitamins & Minerals', 'Vitamins & Minerals'), ('Stomach & Bowel', 'Stomach & Bowel'), ('Cough, Cold & Flu', 'Cough, Cold & Flu'), ('Allergy & Hayfever', 'Allergy & Hayfever'), ('Sexual Health', 'Sexual Health')], default='Not provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='product description', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default='0.00'),
        ),
    ]
